name: Continuos Integration

on: pull_request

jobs:
  continuos-integration:
    runs-on: ubutun-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.jobs
        uses: actions/setup-node@v2
        with:
          node-version: 24.x
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test